version: '3.7'

services:
  questapp:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "8081:8081"
      networks:
        - questapp-network
      environment:
        - DATABASE_URL=jdbc:postgresql://postgres:5432/questapp
        - DATABASE_USERNAME=postgres
        - DATABASE_PASSWORD=65263
      env_file:
        - .env
      depends_on:
        - postgres
  rabbitmq:
    image: rabbitmq:3-management
    hostname: my_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - questapp-network
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - ./rabbitmq-config:/etc/rabbitmq


  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    networks:
      - questapp-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 65263
      POSTGRES_DB: questapp
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}

networks:
  questapp-network:
    driver: bridge
