spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/questapp
    username: postgres
    password: 65263
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: questappnotification@gmail.com
    password: moenbeannfcicxqp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

  sample:
    rabbitmq:
      exchange: default
      queue: firstStepQueue
      routingKey: firstRoute


  config:
    import: optional:file:.env[.properties]
  quest-app:
    jwt-token: ${Jwt_Token:default-key}

server:
  port: 8081
  servlet:
    session:
      timeout: 1800
